version: 2
updates:
- package-ecosystem: "gradle"
  directory: "/"
  target-branch: "main"
  schedule:
    interval: "daily"
    time: "16:00"
  ignore:
  # never bump gradle-api, we depend on specific versions for backwards-compat
  - dependency-name: "dev.gradleplugins:gradle-api"
- package-ecosystem: "gradle"
  directory: "/integration-test/latest"
  target-branch: "main"
  schedule:
    interval: "daily"
    time: "16:00"
