name: Run integration tests
description: Run Gradle integration tests
inputs:
  test-project:
    description: 'Test project to run, from the integration-test folder'
    required: true
    default: 'latest'
  gh-token:
    description: 'GitHub token'
    required: true
runs:
  using: composite
  steps:
  - uses: actions/checkout@v4
  - uses: jdx/mise-action@v2
    with:
      working_directory: integration-test/${{ inputs.test-project }}
  - name: Set JAVA_HOME
    shell: bash
    run: echo "JAVA_HOME=$(mise hook-env -f | grep 'export JAVA_HOME' | cut -d'=' -f2)" >> $GITHUB_ENV
  - name: Fetch maven repo
    uses: actions/download-artifact@v4
    with:
      name: gradle-plugin-repo
      path: build/maven-repo/
  - name: accept Android SDK licenses
    run: yes | cmdline-tools/latest/bin/sdkmanager --licenses || true
    shell: bash
    working-directory: /usr/local/lib/android/sdk
  - name: Run latest tests
    shell: bash
    env:
      EW_API_TOKEN: ${{ inputs.gh-token }}
    working-directory: integration-test/${{ inputs.test-project }}
    run: |
      echo "Using java: $(java -version)"
      echo "Java location: $(which java)"
      echo "JAVA_HOME: $JAVA_HOME"
      ./gradlew :testWithEmulatorWtf
