name: Run integration tests
description: Run Gradle integration tests
inputs:
  jdk-version:
    description: 'JDK version to use'
    required: true
    default: '21'
  test-project:
    description: 'Test project to run, from the integration-test folder'
    required: true
    default: 'latest'
  gh-token:
    description: 'GitHub token'
    required: true
  config-cache:
    description: 'Enable Gradle configuration cache'
    required: false
    default: 'false'
runs:
  using: composite
  steps:
  - uses: actions/checkout@v4
  - name: Setup JDK
    uses: actions/setup-java@v4
    with:
      distribution: 'zulu'
      java-version: ${{ inputs.jdk-version }}
      cache: gradle
  - name: Fetch maven repo
    uses: actions/download-artifact@v4
    with:
      name: gradle-plugin-repo
      path: build/maven-repo/
  - name: accept Android SDK licenses
    run: yes | cmdline-tools/latest/bin/sdkmanager --licenses || true
    shell: bash
    working-directory: /usr/local/lib/android/sdk
  - name: Run latest tests
    shell: bash
    env:
      EW_API_TOKEN: ${{ inputs.gh-token }}
    working-directory: integration-test/${{ inputs.test-project }}
    run: |
      CONFIG_CACHE_ARG="--no-configuration-cache"
      if [ "${{ inputs.configuration-cache }}" == "true" ]; then
        CONFIG_CACHE_ARG="--configuration-cache"
      fi
      ./gradlew :testWithEmulatorWtf ewPixel7api33DebugAndroidTest :app:validateBaselineProfile $CONFIG_CACHE_ARG

