name: Run integration tests
description: Run Gradle integration tests
inputs:
  test-project:
    description: 'Test project to run, from the integration-test folder'
    required: true
    default: 'latest'
  oidc-configuration-id:
    description: 'OIDC configuration ID for emulator.wtf'
    required: true
  config-cache:
    description: 'Enable Gradle configuration cache'
    required: false
    default: 'false'
runs:
  using: composite
  steps:
  - uses: actions/checkout@v4
  - uses: jdx/mise-action@v2
    with:
      working_directory: integration-test/${{ inputs.test-project }}
  - name: Set JAVA_HOME
    working-directory: integration-test/${{ inputs.test-project }}
    shell: bash
    run: echo "JAVA_HOME=$(mise hook-env -f | grep 'export JAVA_HOME' | cut -d'=' -f2)" >> $GITHUB_ENV
  - uses: emulator-wtf/configure-credentials@v1
    with:
      oidc-configuration-id: ${{ inputs.oidc-configuration-id }}
  - name: Fetch maven repo
    uses: actions/download-artifact@v4
    with:
      name: gradle-plugin-repo
      path: build/maven-repo/
  - name: accept Android SDK licenses
    run: yes | cmdline-tools/latest/bin/sdkmanager --licenses || true
    shell: bash
    working-directory: /usr/local/lib/android/sdk
  - name: Run latest tests
    shell: bash
    working-directory: integration-test/${{ inputs.test-project }}
    run: |
      CONFIG_CACHE_ARG="--no-configuration-cache"
      if [ "${{ inputs.config-cache }}" == "true" ]; then
        CONFIG_CACHE_ARG="--configuration-cache"
      fi
      ./gradlew :testWithEmulatorWtf ewPixel7api33DebugAndroidTest :app:validateBaselineProfile $CONFIG_CACHE_ARG
